In [1]:
import os
import pandas as pd
from urllib import request
from bs4 import BeautifulSoup
from datetime import date, timedelta
from time import sleep, strftime
url = "https://www.set.or.th/en/market/product/stock/quote/"

input_file = 'name-ttl.csv'
current_dir = '../Daily'
input_dir = os.path.join(os.path.dirname(current_dir), 'Data')
output_dir = os.path.join(os.path.dirname(current_dir), 'Data')
print(input_dir, output_dir)

..\Data ..\Data

In [2]:
file_in = os.path.join(input_dir, input_file)
file_out = os.path.join(output_dir, "price-hilo.csv")
print(file_in, file_out)

..\Data\name-ttl.csv ..\Data\price-hilo.csv

In [3]:
def get_stock_data(in_df):

    in_df.columns = ['name']
    
    output_columns = ['name', 'price', 'today_low', 'today_high', 'year_low', 'year_high']
    # Initialize an empty DataFrame with specified columns
    out_df = pd.DataFrame(columns=output_columns)
    
    for index, row in in_df.iterrows():
        name = str(row['name']).upper()
        response = request.urlopen(url + name + '/price')
        html_page = BeautifulSoup(response, 'html.parser')
        
        price = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info').text.strip()        
        if (price == '-'):
            price = '0.00'          
        
        values_low = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder me-auto lh-1')
        today_low = values_low[0].text
        if (today_low == '-'):
            today_low = '0.00'
        
        values_high = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder lh-1')
        today_high = values_high[0].text
        if (today_high == '-'):
            today_high = '0.00'         
        
        year_low = values_low[1].text        
        year_high = values_high[1].text     
        
        # Append row to the DataFrame and print the row
        out_df.loc[len(out_df)] = [name, price, today_low, today_high, year_low, year_high]
#       print(out_df.iloc[-1].to_string(header=False, index=False)) 
        print(','.join(map(str, out_df.iloc[-1])))
        sleep(1)
        
    return out_df  # return the final dataframe with all values populated

In [4]:
start_time = strftime("%I:%M %p")
print('Start at: ', start_time)

Start at:  01:42 PM

In [5]:
df = pd.read_csv(file_in, header=None)
out_df = get_stock_data(df)

ACE,1.53,1.53,1.55,1.40,2.66
ADVANC,215.00,215.00,216.00,194.00,231.00
AEONTS,152.50,152.00,152.50,145.00,208.00
AH,28.50,28.25,29.25,25.50,39.25
AIE,1.39,1.38,1.41,1.16,3.12
AIMIRT,10.50,10.50,10.60,10.00,12.50
AIT,3.76,3.74,3.78,3.60,6.85
AJ,6.40,6.30,6.40,6.10,13.50
AMATA,22.30,22.20,22.60,19.40,27.25
ANAN,0.84,0.83,0.85,0.70,1.49
AOT,59.75,59.25,60.25,58.00,75.50
AP,10.90,10.90,11.00,10.10,12.80
ASIAN,6.85,6.80,6.95,5.95,14.00
ASK,19.70,19.50,19.80,19.20,34.50
ASP,2.82,2.80,2.84,2.68,3.24
ASW,8.30,8.15,8.30,7.65,9.10
AWC,3.78,3.76,3.90,3.40,6.20
BA,14.80,14.60,14.90,11.80,17.60
BAM,8.00,7.95,8.10,7.75,16.40
BANPU,6.40,6.40,6.50,6.25,12.60
BAY,27.25,26.75,27.25,26.75,34.00
BBL,144.50,144.50,146.00,143.50,175.00
BCH,22.90,22.70,23.00,16.60,23.00
BCP,40.75,40.50,41.00,28.75,45.25
BCPG,8.20,8.20,8.30,8.15,10.60
BCT,59.00,59.00,59.00,48.00,61.00
BDMS,27.25,27.25,27.50,25.00,30.75
BE8,28.00,27.50,28.00,27.00,63.41
BEAUTY,0.62,0.61,0.63,0.42,1.63
BEC,4.80,4.74,4.86,4.74,10.80
BEM,7.30,7.30,7.50,7.35,10.10
BGC,7.70,7.65,7.70,7.15,10.40
BGRIM,26.50,26.00,26.50,21.80,42.75
BH,241.00,240.00,244.00,204.00,272.00
BJC,24.60,24.60,25.25,24.20,40.50
BKI,306.00,306.00,308.00,278.00,321.00
BLA,19.10,19.10,19.30,19.10,32.25
BLAND,0.76,0.75,0.77,0.67,1.06
BPP,14.00,14.00,14.10,13.00,17.50
BTS,6.80,6.70,6.85,5.40,8.75
BTSGIF,3.50,3.48,3.52,3.26,3.96
CBG,74.75,74.25,75.50,61.25,106.00
CENTEL,42.00,41.50,42.00,40.75,58.25
CHG,3.20,3.16,3.22,2.60,4.04
CK,20.80,20.80,21.20,17.80,23.80
CKP,3.82,3.82,3.88,2.98,4.74
COM7,21.60,21.30,21.80,21.40,33.25
CPALL,52.25,52.00,53.50,50.50,70.25
CPAXT,27.75,27.50,28.25,25.25,43.00
CPF,17.20,17.10,17.80,17.60,24.10
CPN,65.25,64.50,65.50,60.50,75.50
CPNCG,6.55,6.55,6.60,4.20,11.70
CPNREIT,11.30,11.20,11.30,9.40,20.40
CPTGF,5.55,5.50,5.55,4.82,7.85
CRC,34.75,34.25,35.00,34.00,47.50
DCC,1.62,1.61,1.63,1.37,2.90
DCON,0.46,0.45,0.47,0.39,0.55
DELTA,85.00,84.50,86.00,70.50,119.50
DIF,8.00,7.95,8.05,7.25,13.70
DOHOME,10.10,10.00,10.20,8.60,15.15
DRT,8.20,8.15,8.20,7.40,8.55
EA,38.00,37.50,38.50,37.75,91.25
EASTW,4.14,4.12,4.16,4.02,5.50
ECL,1.40,1.39,1.41,1.39,2.16
EGATIF,5.90,5.90,5.95,5.30,7.00
EGCO,129.00,128.50,129.50,114.50,176.50
EPG,7.80,7.70,7.85,6.00,9.25
FORTH,19.50,19.40,19.80,19.00,46.25
FPT,15.00,15.00,15.00,14.20,15.50
FSMART,7.00,6.90,7.05,6.60,17.50
FTREIT,10.10,10.10,10.20,9.34,12.29
GC,5.35,5.30,5.40,4.90,6.75
GFPT,11.20,11.00,11.30,9.70,13.70
GGC,8.95,8.90,9.00,7.90,15.20
GLOBAL,15.20,15.10,15.30,14.60,20.35
GPSC,48.75,48.00,49.00,37.00,75.00
GRAMMY,6.25,6.25,6.30,6.10,11.10
GULF,44.25,44.25,45.00,41.50,54.75
GUNKUL,2.88,2.88,2.92,2.24,5.10
GVREIT,5.95,5.90,6.00,5.45,9.90
HANA,49.75,49.25,50.25,36.00,66.25
HFT,4.46,4.46,4.46,3.94,6.95
HMPRO,10.70,10.50,10.70,10.60,15.10
HTC,15.60,15.60,15.80,14.88,21.25
ICHI,16.80,16.60,16.90,11.40,17.60
III,9.95,9.60,10.00,8.75,16.10
ILM,21.70,21.60,22.10,17.70,26.00
IMH,7.60,7.60,7.65,7.20,14.80
IMPACT,12.30,12.30,12.40,11.60,14.30
INOX,0.58,0.57,0.59,0.53,1.05
INTUCH,72.25,71.75,72.50,67.75,78.00
IP,8.85,8.80,9.05,8.15,15.70
IRPC,1.93,1.91,1.93,1.89,3.20
IVL,23.60,23.30,23.90,23.00,42.50
JASIF,6.10,6.10,6.20,5.70,8.30
JMART,15.00,14.80,15.60,13.10,39.75
JMT,22.20,21.70,23.80,23.30,65.25
KBANK,122.00,120.50,122.50,119.00,148.50
KCE,48.25,47.75,48.50,35.50,58.50
KEX,5.40,5.35,5.50,3.86,19.50
KGI,4.66,4.66,4.68,4.34,5.25
KKP,47.00,46.75,47.50,45.75,71.75
KSL,2.58,2.58,2.64,2.46,3.84
KTB,16.40,16.10,16.50,15.60,20.50
KTC,43.25,42.75,43.50,40.50,59.50
KYE,288.00,288.00,288.00,275.00,321.00
LALIN,8.00,8.00,8.05,7.85,9.50
LANNA,15.10,15.10,15.20,13.80,17.30
LH,7.60,7.45,7.60,7.20,10.00
LHFG,1.00,0.99,1.01,0.98,1.23
LHK,4.36,4.36,4.38,4.14,5.35
LIT,1.10,1.08,1.11,0.96,1.87
LPF,13.30,13.30,13.50,11.30,14.50
LPH,4.92,4.88,4.92,4.80,5.75
LPN,3.84,3.84,3.88,3.74,4.88
M,36.50,36.00,36.50,35.00,58.25
MAJOR,14.50,14.30,14.50,12.80,19.20
MBAX,3.44,3.44,3.46,3.06,5.65
MC,13.40,13.30,13.60,9.85,14.20
MCS,6.35,6.35,6.40,5.90,10.30
MEGA,43.00,43.00,43.50,34.75,52.50
MINT,28.00,27.50,28.00,25.75,35.00
MST,11.00,10.90,11.00,10.50,11.90
MTC,41.25,40.50,42.00,30.75,47.00
NER,4.92,4.92,5.10,4.40,6.70
NOBLE,4.04,4.02,4.04,3.46,5.90
ONEE,4.12,4.02,4.16,3.52,8.15
OR,18.30,18.10,18.40,17.60,23.70
ORI,8.05,8.00,8.25,8.05,12.90
OSP,21.40,21.20,21.70,20.70,33.00
PAP,2.64,2.60,2.64,2.26,4.08
PCSGH,5.30,5.30,5.35,4.40,5.70
PDG,2.52,2.52,2.58,2.40,3.52
PLANB,8.80,8.75,8.90,7.50,10.10
POPF,6.40,6.35,6.50,5.60,11.70
PREB,6.45,6.40,6.50,5.95,9.60
PRM,5.75,5.70,5.80,4.92,8.10
PSH,12.20,12.10,12.20,11.90,14.00
PSL,8.05,8.00,8.35,7.20,16.80
PTG,8.70,8.65,8.80,7.70,14.90
PTL,10.10,10.10,10.30,9.60,26.50
PTT,33.75,33.75,34.25,29.50,36.50
PTTEP,148.50,148.50,150.50,134.50,175.00
PTTGC,34.25,34.00,34.75,31.75,52.50
QH,2.20,2.18,2.20,2.16,2.48
RATCH,30.25,30.00,30.25,29.75,43.75
RBF,12.80,12.70,12.90,8.95,14.60
RCL,26.00,25.75,26.25,18.50,33.00
RJH,27.00,26.75,27.25,24.70,31.50
ROJNA,6.05,5.95,6.10,5.45,7.35
RS,13.50,13.40,13.50,13.20,16.73
S11,0.00,0.00,0.00,3.48,5.40
SABUY,5.00,5.00,5.05,4.86,13.60
SAPPE,84.50,83.50,85.00,37.00,100.00
SAT,18.30,18.30,18.60,17.10,21.80
SAWAD,38.75,38.25,39.00,37.75,61.00
SC,3.26,3.24,3.30,2.96,4.78
SCB,105.00,104.00,105.50,95.50,118.50
SCC,269.00,268.00,272.00,271.00,355.00
SCCC,133.50,133.50,134.50,130.00,163.00
SCGP,31.50,31.50,32.75,31.50,56.00
SENA,2.36,2.34,2.38,2.26,4.06
SGP,8.00,7.95,8.10,7.60,10.20
SINGER,10.30,10.00,10.50,7.20,29.25
SIRI,1.74,1.73,1.76,1.49,2.10
SIS,23.60,23.40,24.00,14.90,29.00
SJWD,13.00,12.80,13.00,10.80,22.30
SKN,4.56,4.56,4.62,3.98,5.60
SKR,10.00,9.95,10.10,8.75,13.80
SMPC,9.55,9.55,9.60,9.45,13.50
SNC,8.55,8.30,8.65,8.30,14.70
SPALI,18.90,18.90,19.20,17.10,24.80
SPC,61.00,61.00,61.00,60.25,66.75
SPCG,12.20,12.20,12.30,12.00,15.10
SPRC,8.00,7.90,8.05,7.20,11.80
SPRIME,4.80,4.78,4.80,4.68,7.35
SSP,8.20,8.20,8.30,5.30,9.36
STA,15.70,15.60,16.70,12.10,26.00
STANLY,220.00,219.00,223.00,171.50,233.00
STEC,8.30,8.25,8.40,7.95,14.50
STGT,6.95,6.90,7.15,5.70,12.00
SUPER,0.42,0.40,0.42,0.40,0.70
SUPEREIF,6.25,6.25,6.30,5.70,9.85
SVI,6.75,6.70,6.85,6.70,10.70
SYNEX,10.80,10.70,11.20,8.90,17.60
TASCO,16.30,16.30,16.50,15.60,21.00
TCAP,52.00,51.00,52.00,42.00,52.50
TFFIF,7.10,7.10,7.15,6.00,8.30
TFG,3.56,3.54,3.60,3.04,5.80
THANI,2.60,2.56,2.60,2.52,4.32
THG,48.75,48.25,50.00,49.75,72.00
TIDLOR,21.50,21.40,21.80,18.60,28.00
TIPH,29.75,29.50,30.00,28.50,53.75
TIPCO,9.40,9.35,9.45,8.75,12.60
TISCO,97.25,96.75,97.25,89.50,103.50
TK,5.55,5.55,5.55,4.92,8.90
TKN,10.40,10.40,10.60,8.65,14.40
TKS,6.80,6.70,6.90,5.00,13.90
TMT,6.05,6.05,6.15,6.00,8.45
TMW,50.25,49.75,50.25,35.00,53.25
TOA,22.30,22.20,22.50,19.20,35.00
TOP,53.00,52.50,53.00,42.25,60.25
TPIPL,1.42,1.41,1.43,1.32,1.86
TPIPP,3.38,3.38,3.40,3.22,3.54
TQM,28.75,28.50,29.00,24.70,44.00
TR,42.00,42.00,42.00,41.25,48.00
TRUE,5.60,5.35,5.65,5.00,9.00
TSE,2.06,2.04,2.12,1.64,2.64
TSTH,0.81,0.80,0.82,0.77,1.22
TTA,6.25,6.20,6.45,4.74,8.30
TTB,1.79,1.78,1.81,1.29,1.81
TTLPF,0.00,0.00,0.00,17.90,23.20
TTW,9.35,9.35,9.45,8.15,9.75
TU,15.30,15.30,15.60,12.40,16.50
TVO,21.50,21.20,21.50,20.50,29.25
TYCN,2.60,2.58,2.62,2.20,3.20
UTP,11.80,11.70,11.90,10.10,16.40
VGI,1.72,1.70,1.74,1.72,5.10
VIBHA,1.83,1.83,1.86,1.72,2.80
VNG,3.58,3.50,3.60,3.56,5.90
WHA,4.58,4.56,4.68,3.70,5.55
WHAIR,5.45,5.40,5.50,5.30,8.10
WHART,9.95,9.90,9.95,8.95,11.90
WHAUP,4.08,4.06,4.12,3.48,4.28
WICE,5.80,5.80,6.00,5.35,12.50
WORK,10.60,10.60,11.00,10.50,18.80

In [6]:
end_time = strftime("%I:%M %p")
print('End at: ', end_time)

End at:  01:53 PM

In [7]:
out_df['price'] = out_df['price'].astype('float')
out_df['today_low'] = out_df['today_low'].astype('float')
out_df['today_high'] = out_df['today_high'].astype('float')
out_df['year_low'] = out_df['year_low'].astype('float')
out_df['year_high'] = out_df['year_high'].astype('float')

In [8]:
out_df.query('today_low <= year_low')

      name   price  today_low  today_high  year_low  year_high
20     BAY   27.25      26.75       27.25     26.75      34.00
29     BEC    4.80       4.74        4.86      4.74      10.80
30     BEM    7.30       7.30        7.50      7.35      10.10
36     BLA   19.10      19.10       19.30     19.10      32.25
46    COM7   21.60      21.30       21.80     21.40      33.25
49     CPF   17.20      17.10       17.80     17.60      24.10
61      EA   38.00      37.50       38.50     37.75      91.25
63     ECL    1.40       1.39        1.41      1.39       2.16
82   HMPRO   10.70      10.50       10.70     10.60      15.10
96     JMT   22.20      21.70       23.80     23.30      65.25
128    ORI    8.05       8.00        8.25      8.05      12.90
151    S11    0.00       0.00        0.00      3.48       5.40
158    SCC  269.00     268.00      272.00    271.00     355.00
160   SCGP   31.50      31.50       32.75     31.50      56.00
170    SNC    8.55       8.30        8.65      8.30      14.70
181  SUPER    0.42       0.40        0.42      0.40       0.70
183    SVI    6.75       6.70        6.85      6.70      10.70
190    THG   48.75      48.25       50.00     49.75      72.00
211  TTLPF    0.00       0.00        0.00     17.90      23.20
217    VGI    1.72       1.70        1.74      1.72       5.10
219    VNG    3.58       3.50        3.60      3.56       5.90

In [9]:
out_df.query('today_low <= year_low').shape[0]

21

In [10]:
out_df.query('today_high >= year_high')

    name  price  today_low  today_high  year_low  year_high
22   BCH  22.90      22.70       23.00     16.60      23.00
210  TTB   1.79       1.78        1.81      1.29       1.81

In [11]:
out_df.query('today_high >= year_high').shape[0]

2

In [12]:
today = date.today()
today

datetime.date(2024, 1, 23)

In [13]:
out_df['updated_at'] = pd.to_datetime(today)

In [14]:
out_df.to_csv(file_out, index=False)  # write the output dataframe to a new CSV file