In [1]:
import os
import pandas as pd
from urllib import request
from bs4 import BeautifulSoup
from time import sleep, strftime
url = "https://www.set.or.th/en/market/product/stock/quote/"

input_file = 'name-ttl.csv'
current_dir = '../Daily'
input_dir = os.path.join(os.path.dirname(current_dir), 'Data')
output_dir = os.path.join(os.path.dirname(current_dir), 'Data')
file_in = os.path.join(input_dir, input_file)
file_out = os.path.join(output_dir, "price-hilo.csv")
print(file_in, file_out)

..\Data\name-ttl.csv ..\Data\price-hilo.csv

In [2]:
def get_stock_data(input_df):
    # Assuming the first row is header, use `usecols` parameter of read_csv method to skip it.
    input_df = pd.read_csv(file_in, header=None)
    input_df.columns = ['Name']
    
    output_columns = ['name', 'today_low', 'today_high', 'year_low', 'year_high']
    data = []
    for index, row in input_df.iterrows():
        name = str(row['Name']).upper()
        response = request.urlopen(url + name + '/price')
        html_page = BeautifulSoup(response, 'html.parser')
        
        values_low = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder me-auto lh-1')
        today_low = values_low[0].text
        if (today_low == '-'):
            today_low = '0.00'
        
        values_high = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder lh-1')
        today_high = values_high[0].text
        if (today_high == '-'):
            today_high = '0.00'         
        
        year_low = values_low[1].text        
        year_high = values_high[1].text        
        data.append([name,today_low,today_high,year_low,year_high]) 
        sleep(1)   # to avoid overloading the server and getting blocked
        print([name,today_low,today_high,year_low,year_high]) 
        sleep(5)
        
    output_df = pd.DataFrame(data, columns=output_columns)
    return output_df  # return the final dataframe with all values populated

In [3]:
start_time = strftime("%I:%M %p")
print('Start at: ', start_time)

Start at:  04:21 PM

In [4]:
df = pd.read_csv(file_in, header=None)
output_df = get_stock_data(df)

['ACE', '1.52', '1.56', '1.40', '2.68']
['ADVANC', '215.00', '217.00', '194.00', '231.00']
['AEONTS', '152.00', '154.00', '145.00', '208.00']
['AH', '29.00', '30.50', '25.50', '39.25']
['AIE', '1.36', '1.42', '1.16', '3.12']
['AIMIRT', '10.40', '10.60', '10.00', '12.50']
['AIT', '3.76', '3.82', '3.60', '6.85']
['AJ', '6.30', '6.60', '6.10', '13.60']
['AMATA', '22.20', '22.90', '19.40', '27.25']
['ANAN', '0.83', '0.85', '0.70', '1.49']
['AOT', '60.50', '61.25', '58.00', '75.50']
['AP', '10.90', '11.20', '10.10', '12.80']
['ASIAN', '6.80', '7.00', '5.95', '14.00']
['ASK', '19.50', '20.00', '19.20', '34.50']
['ASP', '2.80', '2.84', '2.68', '3.24']
['ASW', '8.20', '8.25', '7.65', '9.10']
['AWC', '3.84', '3.92', '3.40', '6.20']
['BA', '14.70', '15.00', '11.80', '17.60']
['BAM', '7.90', '8.15', '7.75', '16.50']
['BANPU', '6.40', '6.60', '6.25', '12.70']
['BAY', '26.75', '27.50', '26.75', '34.00']
['BBL', '143.50', '145.50', '144.00', '175.00']
['BCH', '22.30', '23.00', '16.60', '23.00']
['BCP', '39.75', '40.75', '28.75', '45.25']
['BCPG', '8.20', '8.35', '8.15', '10.60']
['BCT', '58.00', '59.25', '48.00', '61.00']
['BDMS', '27.00', '27.75', '25.00', '30.75']
['BE8', '27.50', '28.25', '27.00', '63.41']
['BEAUTY', '0.60', '0.66', '0.42', '1.63']
['BEC', '4.74', '4.88', '4.78', '10.80']
['BEM', '7.35', '7.50', '7.40', '10.10']
['BGC', '7.55', '7.75', '7.15', '10.40']
['BGRIM', '26.00', '26.50', '21.80', '42.75']
['BH', '239.00', '244.00', '204.00', '272.00']
['BJC', '24.90', '25.50', '24.20', '40.50']
['BKI', '307.00', '309.00', '278.00', '321.00']
['BLA', '19.10', '19.50', '19.10', '32.25']
['BLAND', '0.75', '0.78', '0.67', '1.06']
['BPP', '14.00', '14.30', '13.00', '17.50']
['BTS', '6.65', '6.90', '5.40', '8.75']
['BTSGIF', '3.50', '3.52', '3.26', '3.96']
['CBG', '73.50', '76.25', '61.25', '106.00']
['CENTEL', '41.25', '42.00', '40.75', '58.25']
['CHG', '3.10', '3.24', '2.60', '4.04']
['CK', '20.70', '21.30', '17.80', '24.10']
['CKP', '3.80', '3.88', '2.98', '4.74']
['COM7', '21.50', '22.10', '21.40', '33.25']
['CPALL', '52.00', '53.75', '50.50', '70.25']
['CPAXT', '27.75', '28.50', '25.25', '43.00']
['CPF', '17.60', '18.20', '17.90', '24.20']
['CPN', '64.50', '66.00', '60.50', '75.50']
['CPNCG', '6.55', '6.65', '4.20', '11.70']
['CPNREIT', '11.20', '11.30', '9.40', '21.30']
['CPTGF', '5.45', '5.60', '4.82', '7.85']
['CRC', '34.00', '35.25', '35.00', '47.50']
['DCC', '1.60', '1.63', '1.37', '2.90']
['DCON', '0.46', '0.48', '0.39', '0.55']
['DELTA', '83.25', '85.25', '70.50', '119.50']
['DIF', '8.00', '8.15', '7.25', '13.70']
['DOHOME', '10.10', '10.50', '8.60', '15.15']
['DRT', '8.20', '8.25', '7.40', '8.55']
['EA', '38.00', '39.75', '39.00', '91.25']
['EASTW', '4.14', '4.18', '4.02', '5.50']
['ECL', '1.39', '1.41', '1.39', '2.16']
['EGATIF', '5.90', '6.00', '5.30', '7.00']
['EGCO', '128.00', '130.50', '114.50', '176.50']
['EPG', '7.50', '7.85', '6.00', '9.30']
['FORTH', '19.60', '20.10', '19.00', '46.25']
['FPT', '14.80', '15.20', '14.20', '15.50']
['FSMART', '6.90', '7.05', '6.60', '17.50']
['FTREIT', '10.10', '10.20', '9.34', '12.39']
['GC', '5.30', '5.40', '4.90', '6.75']
['GFPT', '10.90', '11.30', '9.70', '13.70']
['GGC', '8.90', '9.00', '7.90', '15.20']
['GLOBAL', '15.00', '15.30', '14.60', '20.35']
['GPSC', '47.75', '49.25', '37.00', '75.00']
['GRAMMY', '6.30', '6.35', '6.10', '11.10']
['GULF', '44.25', '45.25', '41.50', '54.75']
['GUNKUL', '2.84', '2.92', '2.24', '5.15']
['GVREIT', '6.00', '6.15', '5.45', '9.90']
['HANA', '49.00', '51.25', '36.00', '66.25']
['HFT', '4.40', '4.52', '3.94', '6.95']
['HMPRO', '10.60', '10.80', '10.70', '15.10']
['HTC', '15.60', '15.80', '14.75', '21.25']
['ICHI', '16.30', '16.90', '11.40', '17.60']
['III', '9.55', '9.75', '8.75', '16.10']
['ILM', '22.20', '23.30', '17.70', '26.00']
['IMH', '7.45', '7.65', '7.20', '14.80']
['IMPACT', '12.30', '12.60', '11.60', '14.80']
['INOX', '0.58', '0.60', '0.53', '1.05']
['INTUCH', '71.00', '72.00', '67.75', '78.00']
['IP', '8.95', '9.05', '8.15', '15.70']
['IRPC', '1.91', '1.94', '1.89', '3.20']
['IVL', '23.30', '23.70', '23.00', '42.50']
['JASIF', '6.10', '6.30', '5.70', '8.30']
['JMART', '15.40', '16.10', '13.10', '40.00']
['JMT', '23.60', '25.50', '23.30', '67.75']
['KBANK', '119.00', '123.50', '121.50', '148.50']
['KCE', '47.50', '49.00', '35.50', '58.50']
['KEX', '5.35', '5.40', '3.86', '19.50']
['KGI', '4.66', '4.72', '4.34', '5.25']
['KKP', '45.75', '47.25', '47.25', '73.00']
['KSL', '2.64', '2.70', '2.46', '3.84']
['KTB', '15.60', '17.50', '16.00', '20.50']
['KTC', '42.75', '43.50', '40.50', '59.50']
['KYE', '287.00', '288.00', '275.00', '321.00']
['LALIN', '8.00', '8.05', '7.85', '9.50']
['LANNA', '15.00', '15.20', '13.80', '17.30']
['LH', '7.50', '7.65', '7.20', '10.00']
['LHFG', '0.99', '1.01', '0.98', '1.23']
['LHK', '4.34', '4.38', '4.14', '5.35']
['LIT', '1.10', '1.13', '0.96', '1.87']
['LPF', '13.30', '13.50', '11.30', '14.50']
['LPH', '4.88', '4.94', '4.80', '5.75']
['LPN', '3.84', '3.90', '3.74', '4.88']
['M', '35.75', '36.50', '35.00', '58.25']
['MAJOR', '14.10', '14.60', '12.80', '19.20']
['MBAX', '3.44', '3.48', '3.06', '5.65']
['MC', '13.40', '13.80', '9.85', '14.20']
['MCS', '6.30', '6.40', '5.90', '10.30']
['MEGA', '42.25', '43.25', '34.75', '52.50']
['MINT', '27.00', '27.75', '25.75', '35.00']
['MST', '10.90', '11.00', '10.50', '11.90']
['MTC', '40.50', '42.75', '30.75', '47.00']
['NER', '5.00', '5.15', '4.40', '6.70']
['NOBLE', '3.98', '4.04', '3.46', '5.90']
['ONEE', '4.02', '4.16', '3.52', '8.25']
['OR', '18.10', '18.50', '17.60', '23.80']
['ORI', '8.20', '8.40', '8.05', '12.90']
['OSP', '21.10', '21.70', '20.70', '33.00']
['PAP', '2.60', '2.66', '2.26', '4.08']
['PCSGH', '5.30', '5.35', '4.40', '5.70']
['PDG', '2.52', '2.58', '2.40', '3.52']
['PLANB', '8.65', '8.90', '7.50', '10.10']
['POPF', '6.40', '6.50', '5.60', '11.70']
['PREB', '6.45', '6.60', '5.95', '9.60']
['PRM', '5.70', '5.90', '4.92', '8.10']
['PSH', '12.00', '12.20', '11.90', '14.00']
['PSL', '8.30', '8.55', '7.20', '16.80']
['PTG', '8.60', '8.80', '7.70', '14.90']
['PTL', '10.10', '10.30', '9.60', '27.00']
['PTT', '33.75', '34.25', '29.50', '36.50']
['PTTEP', '148.00', '150.00', '134.50', '175.00']
['PTTGC', '34.25', '35.00', '31.75', '52.50']
['QH', '2.18', '2.22', '2.16', '2.48']
['RATCH', '29.75', '30.50', '29.75', '44.00']
['RBF', '12.80', '13.40', '8.95', '14.60']
['RCL', '26.00', '26.75', '18.50', '33.00']
['RJH', '26.75', '27.25', '24.70', '31.50']
['ROJNA', '6.00', '6.20', '5.45', '7.35']
['RS', '13.40', '13.50', '13.20', '16.73']
['S11', '3.84', '3.90', '3.48', '5.40']
['SABUY', '5.00', '5.05', '4.86', '13.60']
['SAPPE', '82.50', '85.50', '37.00', '100.00']
['SAT', '18.30', '18.60', '17.10', '21.80']
['SAWAD', '37.75', '39.25', '38.75', '61.00']
['SC', '3.24', '3.32', '2.96', '4.78']
['SCB', '103.00', '105.50', '95.50', '118.50']
['SCC', '271.00', '274.00', '272.00', '357.00']
['SCCC', '133.00', '135.00', '130.00', '163.00']
['SCGP', '31.50', '32.25', '31.50', '56.00']
['SENA', '2.36', '2.40', '2.26', '4.06']
['SGP', '7.95', '8.05', '7.60', '10.20']
['SINGER', '10.30', '11.00', '7.20', '29.25']
['SIRI', '1.74', '1.77', '1.49', '2.10']
['SIS', '23.90', '24.50', '14.90', '29.00']
['SJWD', '12.70', '13.10', '10.80', '22.30']
['SKN', '4.56', '4.66', '3.98', '5.60']
['SKR', '10.00', '10.10', '8.75', '13.80']
['SMPC', '9.45', '9.70', '9.50', '13.50']
['SNC', '8.65', '8.90', '8.30', '14.70']
['SPALI', '18.90', '19.30', '17.10', '24.80']
['SPC', '0.00', '0.00', '60.25', '66.75']
['SPCG', '12.20', '12.40', '12.00', '15.10']
['SPRC', '7.85', '7.95', '7.20', '11.80']
['SPRIME', '4.78', '4.84', '4.68', '7.35']
['SSP', '8.20', '8.35', '5.30', '9.36']
['STA', '16.40', '16.90', '12.10', '26.00']
['STANLY', '213.00', '222.00', '171.50', '233.00']
['STEC', '8.30', '8.65', '7.95', '14.60']
['STGT', '7.00', '7.15', '5.70', '12.00']
['SUPER', '0.40', '0.42', '0.40', '0.70']
['SUPEREIF', '6.20', '6.40', '5.70', '9.85']
['SVI', '6.70', '6.80', '6.70', '10.70']
['SYNEX', '10.90', '11.30', '8.90', '17.60']
['TASCO', '16.20', '16.50', '15.60', '21.00']
['TCAP', '50.75', '52.25', '42.00', '52.50']
['TFFIF', '7.05', '7.15', '6.00', '8.30']
['TFG', '3.56', '3.64', '3.04', '5.80']
['THANI', '2.56', '2.62', '2.52', '4.32']

['THG', '49.75', '52.25', '49.75', '72.00']
['TIDLOR', '21.30', '22.00', '18.60', '28.00']
['TIPH', '29.25', '30.50', '28.50', '53.75']
['TIPCO', '9.35', '9.40', '8.75', '12.60']
['TISCO', '97.25', '98.00', '89.50', '103.50']
['TK', '5.50', '5.55', '4.92', '8.90']
['TKN', '10.40', '10.80', '8.65', '14.40']
['TKS', '6.75', '6.95', '5.00', '13.90']
['TMT', '6.10', '6.15', '6.00', '8.45']
['TMW', '49.00', '50.50', '35.00', '53.25']
['TOA', '22.30', '22.80', '19.20', '35.00']
['TOP', '52.00', '53.00', '42.25', '60.25']
['TPIPL', '1.41', '1.43', '1.32', '1.87']
['TPIPP', '3.38', '3.42', '3.22', '3.54']
['TQM', '28.75', '29.50', '24.70', '44.00']
['TR', '0.00', '0.00', '41.25', '48.00']
['TRUE', '5.30', '5.50', '5.00', '9.00']
['TSE', '2.02', '2.12', '1.64', '2.64']
['TSTH', '0.81', '0.83', '0.77', '1.22']
['TTA', '6.25', '6.45', '4.74', '8.30']
['TTB', '1.76', '1.81', '1.29', '1.80']
['TTLPF', '17.90', '18.10', '17.90', '23.20']
['TTW', '9.30', '9.45', '8.15', '9.75']
['TU', '15.30', '15.70', '12.40', '16.50']
['TVO', '21.10', '21.50', '20.50', '29.25']
['TYCN', '2.58', '2.58', '2.20', '3.20']
['UTP', '11.70', '11.90', '10.10', '16.40']
['VGI', '1.72', '1.79', '1.77', '5.10']
['VIBHA', '1.83', '1.88', '1.72', '2.80']
['VNG', '3.56', '3.74', '3.56', '5.90']
['WHA', '4.54', '4.64', '3.70', '5.55']
['WHAIR', '5.45', '5.55', '5.30', '8.10']
['WHART', '9.90', '10.00', '8.95', '12.10']
['WHAUP', '4.08', '4.14', '3.48', '4.28']
['WICE', '5.90', '6.10', '5.35', '12.50']
['WORK', '10.60', '11.00', '10.50', '18.80']

In [5]:
output_df['today_low'] = output_df['today_low'].astype('float')
output_df['today_high'] = output_df['today_high'].astype('float')
output_df['year_low'] = output_df['year_low'].astype('float')
output_df['year_high'] = output_df['year_high'].astype('float')

In [6]:
end_time = strftime("%I:%M %p")
print('End at: ', end_time)

End at:  04:48 PM

In [7]:
output_df.query('today_low <= year_low')

      name  today_low  today_high  year_low  year_high
20     BAY      26.75       27.50     26.75      34.00
21     BBL     143.50      145.50    144.00     175.00
29     BEC       4.74        4.88      4.78      10.80
30     BEM       7.35        7.50      7.40      10.10
36     BLA      19.10       19.50     19.10      32.25
49     CPF      17.60       18.20     17.90      24.20
54     CRC      34.00       35.25     35.00      47.50
61      EA      38.00       39.75     39.00      91.25
63     ECL       1.39        1.41      1.39       2.16
82   HMPRO      10.60       10.80     10.70      15.10
97   KBANK     119.00      123.50    121.50     148.50
101    KKP      45.75       47.25     47.25      73.00
103    KTB      15.60       17.50     16.00      20.50
145  RATCH      29.75       30.50     29.75      44.00
155  SAWAD      37.75       39.25     38.75      61.00
158    SCC     271.00      274.00    272.00     357.00
160   SCGP      31.50       32.25     31.50      56.00
169   SMPC       9.45        9.70      9.50      13.50
172    SPC       0.00        0.00     60.25      66.75
181  SUPER       0.40        0.42      0.40       0.70
183    SVI       6.70        6.80      6.70      10.70
190    THG      49.75       52.25     49.75      72.00
205     TR       0.00        0.00     41.25      48.00
211  TTLPF      17.90       18.10     17.90      23.20
217    VGI       1.72        1.79      1.77       5.10
219    VNG       3.56        3.74      3.56       5.90

In [8]:
output_df.query('today_low <= year_low').shape[0]

26

In [9]:
output_df.query('today_high >= year_high')

    name  today_low  today_high  year_low  year_high
22   BCH      22.30       23.00     16.60       23.0
210  TTB       1.76        1.81      1.29        1.8

In [10]:
output_df.query('today_high >= year_high').shape[0]

2

In [11]:
output_df.to_csv(file_out)  # write the output dataframe to a new CSV file