In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

In [2]:
url = 'https://www.bbc.com/sport/football/tables'
r = requests.get(url)
html = r.text
#html

In [3]:
soup = BeautifulSoup(html, 'html.parser')
#soup

In [4]:
table = soup.find('table')
df = pd.read_html(str(table))[0]
df

,Unnamed: 0,Unnamed: 1,Team,P,W,D,L,F,A,GD,Pts,Form
0,1,team hasn't moved,Liverpool,19,12,6,1,39,16,23,42,WWon 2 - 0 against Sheffield United on Decembe...
1,2,team hasn't moved,Aston Villa,20,13,3,4,43,27,16,42,WWon 1 - 0 against Arsenal on December 9th 202...
2,3,team hasn't moved,Man City,19,12,4,3,45,21,24,40,LLost 0 - 1 against Aston Villa on December 6t...
3,4,team hasn't moved,Arsenal,20,12,4,4,37,20,17,40,LLost 0 - 1 against Aston Villa on December 9t...
4,5,team hasn't moved,Tottenham,20,12,3,5,42,29,13,39,WWon 4 - 1 against Newcastle United on Decembe...
5,6,team hasn't moved,West Ham,19,10,3,6,33,30,3,33,WWon 2 - 1 against Tottenham Hotspur on Decemb...
6,7,team hasn't moved,Man Utd,20,10,1,9,22,27,-5,31,LLost 0 - 3 against AFC Bournemouth on Decembe...
7,8,team hasn't moved,Brighton,19,8,6,5,38,33,5,30,WWon 2 - 1 against Brentford on December 6th 2...
8,9,team hasn't moved,Newcastle,19,9,2,8,37,25,12,29,LLost 0 - 3 against Everton on December 7th 20...
9,10,team hasn't moved,Chelsea,20,8,4,8,34,31,3,28,LLost 0 - 2 against Everton on December 10th 2...
10,11,team hasn't moved,Wolves,20,8,4,8,30,31,-1,28,DDrew 1 - 1 against Nottingham Forest on Decem...
11,12,team hasn't moved,Bournemouth,19,7,4,8,28,35,-7,25,WWon 2 - 0 against Crystal Palace on December ...
12,13,team hasn't moved,Fulham,20,7,3,10,28,35,-7,24,WWon 5 - 0 against West Ham United on December...
13,14,team hasn't moved,Crystal Palace,20,5,6,9,22,29,-7,21,LLost 1 - 2 against Liverpool on December 9th ...
14,15,team hasn't moved,Nottm Forest,20,5,5,10,24,35,-11,20,DDrew 1 - 1 against Wolverhampton Wanderers on...
15,16,team hasn't moved,Brentford,19,5,4,10,26,31,-5,19,LLost 1 - 2 against Brighton & Hove Albion on ...
16,17,team hasn't moved,Everton,20,8,2,10,24,28,-4,16,WWon 2 - 0 against Chelsea on December 10th 20...
17,18,team hasn't moved,Luton,19,4,3,12,23,37,-14,15,LLost 3 - 4 against Arsenal on December 5th 20...
18,19,team hasn't moved,Burnley,20,3,2,15,20,41,-21,11,DDrew 1 - 1 against Brighton & Hove Albion on ...
19,20,team hasn't moved,Sheff Utd,20,2,3,15,15,49,-34,9,WWon 1 - 0 against Brentford on December 9th 2...
20,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58

In [5]:
#print(df.head())

In [5]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Team', 'P', 'W', 'D', 'L', 'F', 'A', 'GD',
       'Pts', 'Form'],
      dtype='object')

In [6]:
df.drop(columns=['Unnamed: 0','Unnamed: 1','Form'],inplace=True)
df

,Team,P,W,D,L,F,A,GD,Pts
0,Liverpool,19,12,6,1,39,16,23,42
1,Aston Villa,20,13,3,4,43,27,16,42
2,Man City,19,12,4,3,45,21,24,40
3,Arsenal,20,12,4,4,37,20,17,40
4,Tottenham,20,12,3,5,42,29,13,39
5,West Ham,19,10,3,6,33,30,3,33
6,Man Utd,20,10,1,9,22,27,-5,31
7,Brighton,19,8,6,5,38,33,5,30
8,Newcastle,19,9,2,8,37,25,12,29
9,Chelsea,20,8,4,8,34,31,3,28
10,Wolves,20,8,4,8,30,31,-1,28
11,Bournemouth,19,7,4,8,28,35,-7,25
12,Fulham,20,7,3,10,28,35,-7,24
13,Crystal Palace,20,5,6,9,22,29,-7,21
14,Nottm Forest,20,5,5,10,24,35,-11,20
15,Brentford,19,5,4,10,26,31,-5,19
16,Everton,20,8,2,10,24,28,-4,16
17,Luton,19,4,3,12,23,37,-14,15
18,Burnley,20,3,2,15,20,41,-21,11
19,Sheff Utd,20,2,3,15,15,49,-34,9
20,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58,Last updated 31st December 2023 at 15:58

In [7]:
df.drop([20],inplace=True)
df

              Team   P   W  D   L   F   A   GD Pts
0        Liverpool  19  12  6   1  39  16   23  42
1      Aston Villa  20  13  3   4  43  27   16  42
2         Man City  19  12  4   3  45  21   24  40
3          Arsenal  20  12  4   4  37  20   17  40
4        Tottenham  20  12  3   5  42  29   13  39
5         West Ham  19  10  3   6  33  30    3  33
6          Man Utd  20  10  1   9  22  27   -5  31
7         Brighton  19   8  6   5  38  33    5  30
8        Newcastle  19   9  2   8  37  25   12  29
9          Chelsea  20   8  4   8  34  31    3  28
10          Wolves  20   8  4   8  30  31   -1  28
11     Bournemouth  19   7  4   8  28  35   -7  25
12          Fulham  20   7  3  10  28  35   -7  24
13  Crystal Palace  20   5  6   9  22  29   -7  21
14    Nottm Forest  20   5  5  10  24  35  -11  20
15       Brentford  19   5  4  10  26  31   -5  19
16         Everton  20   8  2  10  24  28   -4  16
17           Luton  19   4  3  12  23  37  -14  15
18         Burnley  20   3  2  15  20  41  -21  11
19       Sheff Utd  20   2  3  15  15  49  -34   9

In [9]:
file_name = 'Premier-League.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
osd_file = osd_path + file_name
one_file = one_path + file_name

df.sort_values(['Pts'],ascending=[False]).to_csv(output_file, index=False)
df.sort_values(['Pts'],ascending=[False]).to_csv(data_file, index=False)
df.sort_values(['Pts'],ascending=[False]).to_csv(osd_file, index=False)
df.sort_values(['Pts'],ascending=[False]).to_csv(one_file, index=False)